# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pso_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SummaryFrame = QtWidgets.QFrame(self.centralwidget)
        self.SummaryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SummaryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SummaryFrame.setObjectName("SummaryFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SummaryFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SumGraph = QtWidgets.QWidget(self.SummaryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SumGraph.sizePolicy().hasHeightForWidth())
        self.SumGraph.setSizePolicy(sizePolicy)
        self.SumGraph.setObjectName("SumGraph")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SumGraph)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sum_graph_layout = QtWidgets.QVBoxLayout()
        self.sum_graph_layout.setObjectName("sum_graph_layout")
        self.verticalLayout_3.addLayout(self.sum_graph_layout)
        self.horizontalLayout_2.addWidget(self.SumGraph)
        self.OptParam = QtWidgets.QTableView(self.SummaryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptParam.sizePolicy().hasHeightForWidth())
        self.OptParam.setSizePolicy(sizePolicy)
        self.OptParam.setObjectName("OptParam")
        self.horizontalLayout_2.addWidget(self.OptParam)
        self.verticalLayout.addWidget(self.SummaryFrame)
        self.IterProgBar = QtWidgets.QProgressBar(self.centralwidget)
        self.IterProgBar.setStyleSheet("# QProgressBar::chunk{background-color: lightblue; width: 10px; margin: 1px};\n"
"")
        self.IterProgBar.setProperty("value", 0)
        self.IterProgBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.IterProgBar.setInvertedAppearance(False)
        self.IterProgBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.IterProgBar.setObjectName("IterProgBar")
        self.verticalLayout.addWidget(self.IterProgBar)
        self.MainProgBar = QtWidgets.QProgressBar(self.centralwidget)
        self.MainProgBar.setProperty("value", 0)
        self.MainProgBar.setObjectName("MainProgBar")
        self.verticalLayout.addWidget(self.MainProgBar)
        self.ButtonsFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonsFrame.sizePolicy().hasHeightForWidth())
        self.ButtonsFrame.setSizePolicy(sizePolicy)
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonsFrame)
        self.horizontalLayout.setContentsMargins(10, 1, 10, 1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PauseButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.PauseButton.setIconSize(QtCore.QSize(18, 18))
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout.addWidget(self.PauseButton)
        self.StopContButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.StopContButton.setObjectName("StopContButton")
        self.horizontalLayout.addWidget(self.StopContButton)
        self.verticalLayout.addWidget(self.ButtonsFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PauseButton.setText(_translate("MainWindow", "Pause"))
        self.StopContButton.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
